### ISSUE TITLE
npx expo-doctor giving plugin error

### ISSUE THREAD

**Issue by yash2code** [bugsnag/bugsnag-expo#197]
### Describe the bug
npx expo-doctor command suddenly started giving PluginError: Failed to resolve plugin for module "@bugsnag/plugin-expo-eas-sourcemaps" relative to "/Users/expo/workingdir/build"

### Steps to reproduce
run `npx expo-doctor` 

### Environment
* Bugsnag version: 50:
* Expo SDK version (SDK 50):
* Device : iphone 15, xcode 15.2
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.6.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v20.11.0/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^10.0.2 => 10.0.2
      expo: 50.0.21 => 50.0.21
      expo-router: ~3.4.10 => 3.4.10
      react: 18.2.0 => 18.2.0
      react-native: 0.73.6 => 0.73.6
    npmGlobalPackages:
      eas-cli: 12.5.3
      expo-cli: 6.3.10
    Expo Workflow: bare

<details><summary>Error messages:</summary>

```
Running "expo doctor"
/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89549
throw new (_errors().PluginError)(Failed to resolve plugin for module "${pluginReference}" relative to "${projectRoot}", 'PLUGIN_NOT_FOUND');
^
PluginError: Failed to resolve plugin for module "@bugsnag/plugin-expo-eas-sourcemaps" relative to "/Users/expo/workingdir/build"
at resolvePluginForModule (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89549:9)
at resolveConfigPluginFunctionWithInfo (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89598:7)
at resolveConfigPluginFunction (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:89589:7)
at withStaticPlugin (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88669:70)
at /Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88510:84
at Array.reduce ()
at withPlugins (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:88510:18)
at withConfigPlugins (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:91158:47)
at fillAndReturnConfig (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:90080:78)
at getConfig (/Users/expo/.npm/_npx/c15e4b19a90d9797/node_modules/expo-doctor/build/index.js:90137:10) {
isPluginError: true,
code: 'PLUGIN_NOT_FOUND',
cause: undefined
}
Node.js v18.18.0



```
</details>

**Comment by clr182** [comment]
Hi @yash2code 

The error you’re seeing, PluginError: Failed to resolve plugin for module `@bugsnag/plugin-expo-eas-sourcemaps`, indicates that the Expo Doctor tool is unable to locate the @bugsnag/plugin-expo-eas-sourcemaps plugin.

Please try installing the plugin using `npm install @bugsnag/plugin-expo-eas-sourcemaps` 

Clean your node folder and then running npm install. 

If after installing the plugin using npm the issue still persists then please let us know and we can investigate further.

**Comment by yash2code** [comment]
was issue from expo side. they have resolved it. closing this.
