### ISSUE TITLE
Cannot run bugsnag when using app.config.js (dynamic app.json)

### ISSUE THREAD

**Issue by mrflip** [bugsnag/bugsnag-expo#64]
### Describe the bug

Modern expos allow using app.config.js rather than app.json. 

If app.json is missing, or is missing an `"expo": {}` element, the init command fails:

```
zumthor$ npx bugsnag-expo-cli init
✔ @bugsnag/expo already appears to be installed, do you want to install it and its dependencies anyway? … no
✔ What is your Bugsnag API key? … deadbeef4acab110b32b3a1234567890
> Inserting API key into app.json

  TypeError: Cannot read properties of undefined (reading 'extra')
      at module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/lib/set-api-key.js:9:33)
      at async module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/commands/set-api-key.js:18:15)
      at async module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/commands/init.js:11:3)
      at async go (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/cli.js:39:21) 
```

### Workaround

1. Create a placeholder app.json: `echo '{ "expo": {} }' > app.json`
2. Follow the instructions as given
3. hand-replay the new parts of app.json into the config
4. remove app.json 

### Steps to reproduce

1. switch from app.json to app.config.js
2. run npx bugsnag-exp-cli init
3. dies editing app.json

It will also die if the app.json lacks an `expo` field: i.e. app.json == `{}` yields sadness, app.json = `{ "expo": {} }` yields workaround.

## Example code snippet 

Vanilla repo, change to dynamic config:

```
cd /tmp
expo init foo -t blank
cd foo
# (will attest that the config hasn't changed)
npx expo config --json | jq '. | del(._internal) | { expo: . }' > cfg-vanilla.json
( echo -n "const AppConfig = (" ; cat app.json ; echo ")" ; echo  "export default AppConfig" ) > app.config.js
mv app.json away-app.json
npx expo config --json | jq '. | del(._internal) | { expo: . }' > cfg-dynamic.json

# this will be empty, the configs are the same
diff cfg-dynamic.json cfg-vanilla.json 
```

### Demonstrate the bug:

```
quickbeam main /tmp/foo$ npx bugsnag-expo-cli init

✔ @bugsnag/expo does not appear to be installed, do you want to install it and its dependencies? … yes
✔ If you want to install @bugsnag/expo ^46.0.0 hit enter, otherwise type the version you want … ^46.0.0
> Installing @bugsnag/expo. This could take a while!
✔ What is your Bugsnag API key? … deadbeef4acab110b32b3a1234567890
> Inserting API key into app.json

  Error: Couldn’t find app.json in "/private/tmp/foo". ....

```

### Demonstrate the workaround:

```
/tmp/foo$ echo '{ "expo": {} }' > app.json
/tmp/foo$ npx bugsnag-expo-cli init
/tmp/foo$ cat app.json
```

... then replay the changes from app.json into your config file.

### Environment

* Bugsnag version: 46
* Expo SDK version (e.g. SDK 44): 46
* Device (e.g. iphonex): cli

<details><summary>Error messages:</summary>

```

  TypeError: Cannot read properties of undefined (reading 'extra')
      at module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/lib/set-api-key.js:9:33)
      at async module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/commands/set-api-key.js:18:15)
      at async module.exports (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/commands/init.js:11:3)
      at async go (/Users/flip/.npm/_npx/c6a5a58d15e1cf59/node_modules/bugsnag-expo-cli/cli.js:39:21) 
```
</details>

**Comment by luke-belton** [comment]
Hi @mrflip - thanks for raising this. We're going to investigate and will keep you updated on this thread 👍

**Comment by luke-belton** [comment]
Hi @mrflip - we just released https://github.com/bugsnag/bugsnag-expo/releases/tag/v46.0.2 of `bugsnag-expo`, which includes a [fix](https://github.com/bugsnag/bugsnag-expo/pull/71) for automated installations where apps use `app.config.js` 🎉 

Thanks again for reporting this!
